import { EventEmitter } from "node:events";

/**
 * Bus events delivered over SSE (and used internally to wake long-pollers).
 * These mirror the SSE event spec: message / task_created / task_claimed /
 * task_completed (heartbeat is generated by the SSE writer, not published here).
 */
export type BusEvent =
  | {
      type: "message";
      /** Recipient of a direct message, or null for a broadcast. */
      to: string | null;
      from: string;
      message_id: number;
      subject: string | null;
      /** First 200 chars of the body. */
      preview: string;
    }
  | { type: "task_created"; task_id: string; title: string }
  | { type: "task_claimed"; task_id: string; assignee: string }
  | {
      type: "task_completed";
      task_id: string;
      assignee: string | null;
      result_preview: string | null;
    };

const WAKE_PREFIX = "wake:";
const BUS_EVENT = "bus";

/**
 * In-process pub/sub backing two consumers:
 *  - `wait_for_message` long-polls (per-agent wake-ups), and
 *  - the `/events` SSE endpoint (a filtered firehose).
 *
 * Single process, single emitter — no external broker. If this ever needs to
 * span hosts, swap the emitter for Redis pub/sub behind the same interface.
 */
export class BusEvents {
  private readonly emitter = new EventEmitter();

  constructor() {
    // Many agents may wait/subscribe at once; lift the default 10-listener cap.
    this.emitter.setMaxListeners(0);
  }

  /** Decide whether a bus event is relevant to a given subscriber agent. */
  static isRelevantTo(event: BusEvent, agentId: string): boolean {
    if (event.type !== "message") return true; // task_* events are bus-wide
    if (event.to === null) return event.from !== agentId; // broadcast: not the sender
    return event.to === agentId; // direct: only the recipient
  }

  /**
   * Publish a bus event to SSE subscribers, and wake any long-pollers for the
   * given recipient agents (message events only). Broadcasts pass every
   * recipient so each waiter is woken individually.
   */
  publish(event: BusEvent, wakeAgentIds: string[] = []): void {
    this.emitter.emit(BUS_EVENT, event);
    for (const agentId of wakeAgentIds) {
      this.emitter.emit(`${WAKE_PREFIX}${agentId}`);
    }
  }

  /**
   * Resolve as soon as a message is available for `agentId`, or after
   * `timeoutMs`. Returns true if woken by a message, false on timeout.
   */
  waitForMessage(agentId: string, timeoutMs: number): Promise<boolean> {
    return new Promise((resolve) => {
      const channel = `${WAKE_PREFIX}${agentId}`;
      const onWake = () => {
        clearTimeout(timer);
        resolve(true);
      };
      const timer = setTimeout(() => {
        this.emitter.off(channel, onWake);
        resolve(false);
      }, timeoutMs);
      // Don't let a pending long-poll keep the process alive on shutdown.
      timer.unref?.();
      this.emitter.once(channel, onWake);
    });
  }

  /** Subscribe to the full bus event stream. Returns an unsubscribe function. */
  subscribe(handler: (event: BusEvent) => void): () => void {
    this.emitter.on(BUS_EVENT, handler);
    return () => this.emitter.off(BUS_EVENT, handler);
  }
}

/** Serialize a payload as a single SSE event frame. */
export function formatSseEvent(eventType: string, data: unknown): string {
  return `event: ${eventType}\ndata: ${JSON.stringify(data)}\n\n`;
}

/** First `n` characters of a string, for event previews. */
export function preview(text: string, n = 200): string {
  return text.length > n ? text.slice(0, n) : text;
}
